# Generated by Django 2.2 on 2020-12-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201213_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothing'), ('TE', 'Tech'), ('AC', 'Accessories'), ('PE', 'Pets'), ('AU', 'Auto'), ('HG', 'House & Garden')], max_length=2),
        ),
    ]
